package application.test.jdbc;

import database.utilities.BeanDBAccess;
import java.sql.*;

/**
 * @author Morgan
 */
public class ApplicationTestJDBC extends javax.swing.JFrame {

	private BeanDBAccess beanBDAccess;

	/**
	 * Creates new form APPLICATION_TEST_JDBC
	 */
	public ApplicationTestJDBC() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BDButtonGroup = new javax.swing.ButtonGroup();
        BDChoicePanel = new javax.swing.JPanel();
        BDLabel = new javax.swing.JLabel();
        BDButtonChoicePanel = new javax.swing.JPanel();
        BDSocieteRadioButton = new javax.swing.JRadioButton();
        BDJournalDeBordRadioButton = new javax.swing.JRadioButton();
        BDButtonConnectPanel = new javax.swing.JPanel();
        ConnexionButton = new javax.swing.JButton();
        DesconnectButton = new javax.swing.JButton();
        QueryPanel = new javax.swing.JPanel();
        QueryScrollPane = new javax.swing.JScrollPane();
        QueryTextArea = new javax.swing.JTextArea();
        QueryLabel = new javax.swing.JLabel();
        ExecuteQueryButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultsTextArea = new javax.swing.JTextArea();
        ResultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BDLabel.setText("A quelle base de données souhaitez-vous vous connecter ?");

        BDButtonGroup.add(BDSocieteRadioButton);
        BDSocieteRadioButton.setSelected(true);
        BDSocieteRadioButton.setText("BD_AIRPORT");

        BDButtonGroup.add(BDJournalDeBordRadioButton);
        BDJournalDeBordRadioButton.setText("BD_JOURNALDEBORD");

        javax.swing.GroupLayout BDButtonChoicePanelLayout = new javax.swing.GroupLayout(BDButtonChoicePanel);
        BDButtonChoicePanel.setLayout(BDButtonChoicePanelLayout);
        BDButtonChoicePanelLayout.setHorizontalGroup(
            BDButtonChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BDButtonChoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BDButtonChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BDSocieteRadioButton)
                    .addComponent(BDJournalDeBordRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BDButtonChoicePanelLayout.setVerticalGroup(
            BDButtonChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BDButtonChoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BDSocieteRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BDJournalDeBordRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ConnexionButton.setText("Se connecter");
        ConnexionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnexionButtonActionPerformed(evt);
            }
        });

        DesconnectButton.setText("Se déconnecter");
        DesconnectButton.setEnabled(false);
        DesconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesconnectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BDButtonConnectPanelLayout = new javax.swing.GroupLayout(BDButtonConnectPanel);
        BDButtonConnectPanel.setLayout(BDButtonConnectPanelLayout);
        BDButtonConnectPanelLayout.setHorizontalGroup(
            BDButtonConnectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BDButtonConnectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BDButtonConnectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConnexionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DesconnectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        BDButtonConnectPanelLayout.setVerticalGroup(
            BDButtonConnectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BDButtonConnectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConnexionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DesconnectButton)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BDChoicePanelLayout = new javax.swing.GroupLayout(BDChoicePanel);
        BDChoicePanel.setLayout(BDChoicePanelLayout);
        BDChoicePanelLayout.setHorizontalGroup(
            BDChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BDChoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BDChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BDChoicePanelLayout.createSequentialGroup()
                        .addGroup(BDChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BDLabel)
                            .addComponent(BDButtonChoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BDChoicePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BDButtonConnectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        BDChoicePanelLayout.setVerticalGroup(
            BDChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BDChoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BDButtonChoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BDButtonConnectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        QueryTextArea.setColumns(20);
        QueryTextArea.setRows(5);
        QueryScrollPane.setViewportView(QueryTextArea);

        QueryLabel.setText("Entrez la requête à exécuter :");

        ExecuteQueryButton.setText("Exécuter");
        ExecuteQueryButton.setEnabled(false);
        ExecuteQueryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecuteQueryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QueryPanelLayout = new javax.swing.GroupLayout(QueryPanel);
        QueryPanel.setLayout(QueryPanelLayout);
        QueryPanelLayout.setHorizontalGroup(
            QueryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QueryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QueryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QueryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QueryPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ExecuteQueryButton))
                    .addGroup(QueryPanelLayout.createSequentialGroup()
                        .addComponent(QueryLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        QueryPanelLayout.setVerticalGroup(
            QueryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QueryPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QueryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QueryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExecuteQueryButton))
        );

        ResultsTextArea.setColumns(20);
        ResultsTextArea.setRows(5);
        jScrollPane1.setViewportView(ResultsTextArea);

        ResultLabel.setText("Resultats :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BDChoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(ResultLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QueryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QueryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BDChoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ResultLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 *
	 * @param evt
	 */
    private void ConnexionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnexionButtonActionPerformed
		System.out.println("application_test_jdbc.APPLICATION_TEST_JDBC.ConnexionButtonActionPerformed()");
		try {
			if (BDSocieteRadioButton.isSelected()) {
				beanBDAccess = new BeanDBAccess("com.mysql.jdbc.Driver",
					"jdbc:mysql://localhost:3306/db_airport", "root", "mysql", true);
			} else if (BDJournalDeBordRadioButton.isSelected()) {
				beanBDAccess = new BeanDBAccess("oracle.jdbc.driver.OracleDriver",
					"jdbc:oracle:thin:@localhost:1521/xe", "db_journaldebord", "azerty", true);
			}
			BDSocieteRadioButton.setEnabled(false);
			BDJournalDeBordRadioButton.setEnabled(false);
			ConnexionButton.setEnabled(false);
			DesconnectButton.setEnabled(true);
			ExecuteQueryButton.setEnabled(true);
		} catch (Exception e) {
			System.err.println(e.getMessage());
			beanBDAccess = null;
		}
    }//GEN-LAST:event_ConnexionButtonActionPerformed

	/**
	 *
	 * @param evt
	 */
    private void DesconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesconnectButtonActionPerformed
		try {
			beanBDAccess.Close();
			beanBDAccess = null;

			BDSocieteRadioButton.setEnabled(true);
			BDJournalDeBordRadioButton.setEnabled(true);
			ConnexionButton.setEnabled(true);
			DesconnectButton.setEnabled(false);
			ExecuteQueryButton.setEnabled(false);
			QueryTextArea.setText("");
			ResultsTextArea.setText("");
		} catch (Exception e) {
			System.err.println(e.getMessage());
			beanBDAccess = null;

			BDSocieteRadioButton.setEnabled(true);
			BDJournalDeBordRadioButton.setEnabled(true);
			ConnexionButton.setEnabled(true);
			DesconnectButton.setEnabled(false);
			ExecuteQueryButton.setEnabled(false);
			QueryTextArea.setText("");
			ResultsTextArea.setText("");
		}
    }//GEN-LAST:event_DesconnectButtonActionPerformed

	/**
	 *
	 * @param evt
	 */
    private void ExecuteQueryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecuteQueryButtonActionPerformed
		if (!( "".equals(QueryTextArea.getText()) )) {
			if (QueryTextArea.getText().contains("SELECT ") || QueryTextArea.getText().contains("select ")) {
				ResultSet rs;
				String res = "";
				ResultsTextArea.setText("");

				rs = beanBDAccess.ExecuteQuery(QueryTextArea.getText());
				if (rs != null) {
					try {
						ResultSetMetaData rsmd = rs.getMetaData();
						int nb = rsmd.getColumnCount();
						int i;
						for (i = 1; i < nb; i++) {
							res += rsmd.getColumnLabel(i) + " | ";
						}
						res += rsmd.getColumnLabel(i) + "\n";
						while (rs.next()) {
							for (i = 1; i < nb; i++) {
								res += rs.getObject(i) + " | ";
							}
							res += rs.getObject(i) + "\n";
						}
						ResultsTextArea.setText(res);
					} catch (Exception e) {
						System.err.println(e.getMessage());
					}
				} else {
					ResultsTextArea.setText("Erreur lors de l'execution");
				}
			} else {
				boolean ExecuteUpdate = beanBDAccess.ExecuteUpdate(QueryTextArea.getText());
				if (ExecuteUpdate) {
					ResultsTextArea.setText("Requête excécutée");
				} else {
					ResultsTextArea.setText("Erreur lors de l'execution");
				}
			}
		}
    }//GEN-LAST:event_ExecuteQueryButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ApplicationTestJDBC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ApplicationTestJDBC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ApplicationTestJDBC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ApplicationTestJDBC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				ApplicationTestJDBC atjdbc = new ApplicationTestJDBC();
				atjdbc.setLocationRelativeTo(null);
				atjdbc.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BDButtonChoicePanel;
    private javax.swing.JPanel BDButtonConnectPanel;
    private javax.swing.ButtonGroup BDButtonGroup;
    private javax.swing.JPanel BDChoicePanel;
    private javax.swing.JRadioButton BDJournalDeBordRadioButton;
    private javax.swing.JLabel BDLabel;
    private javax.swing.JRadioButton BDSocieteRadioButton;
    private javax.swing.JButton ConnexionButton;
    private javax.swing.JButton DesconnectButton;
    private javax.swing.JButton ExecuteQueryButton;
    private javax.swing.JLabel QueryLabel;
    private javax.swing.JPanel QueryPanel;
    private javax.swing.JScrollPane QueryScrollPane;
    private javax.swing.JTextArea QueryTextArea;
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JTextArea ResultsTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
