package application.luggage;

import db.airport.models.Flight;
import db.airport.models.Luggage;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import requestresponse.impl.LUGAP.*;
import requestresponse.multithread.abstracts.AbstractApplicationForm;

/**
 *
 * @author Morgan
 */
public class AppLuggageForm extends AbstractApplicationForm {

	//Application variables
	private ArrayList<Flight> listFlights;
	private AppLuggageDialog dialog;

	/**
	 * Creates new form AppLuggageForm
	 */
	public AppLuggageForm() {
		super("appluggage.properties", true);
		initComponents();

		ResponseLUGAP res = (ResponseLUGAP) connectToServer(
			new RequestLUGAP(RequestLUGAP.GET_FLIGHTS, ""));
		if (res != null) {
			if (res.getCode() == ResponseLUGAP.GET_FLIGHTS_OK) {
				listFlights = (ArrayList<Flight>) res.getChargeUtile();
				DefaultListModel<String> dlm = new DefaultListModel<>();
				for (Flight flight : listFlights) {
					dlm.addElement(flight.toString());
				}
				flightList.setModel(dlm);
				flightList.setSelectedIndex(-1);
				flightList.setEnabled(true);
			} else JOptionPane.showMessageDialog(this, res.getChargeUtile(),
				"Erreur", JOptionPane.ERROR_MESSAGE);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flightListLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Application Bagages");

        flightListLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        flightListLabel.setText("Liste des vols : ");

        flightList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        flightList.setEnabled(false);
        flightList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flightListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(flightList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(flightListLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flightListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * 
	 * @param evt
	 */
    private void flightListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flightListMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() > 1) {
			if (flightList.getSelectedIndex() != -1) {
				Flight f = listFlights.get(flightList.getSelectedIndex());
				ResponseLUGAP res = (ResponseLUGAP) connectToServer(new RequestLUGAP(RequestLUGAP.CHOOSE_FLIGHT, f.getId()));
				if (res != null && res.getCode() == ResponseLUGAP.CHOOSE_FLIGHT_OK) {
					dialog = new AppLuggageDialog(this, f.toString(), true, (ArrayList<Luggage>)res.getChargeUtile());
					dialog.setLocationRelativeTo(this);
					dialog.addWindowListener(new WindowAdapter() {
						@Override
						public void windowClosed(java.awt.event.WindowEvent event) {
							sendLogout();
						}
					});
					dialog.setVisible(true);
				} else {
					JOptionPane.showMessageDialog(this, "Erreur lors de la récupération des bagages", "Erreur", JOptionPane.ERROR_MESSAGE);
				}
			}
		}
    }//GEN-LAST:event_flightListMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AppLuggageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				AppLuggageForm alf = new AppLuggageForm();
				alf.setLocationRelativeTo(null);
				alf.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> flightList;
    private javax.swing.JLabel flightListLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
