package application.tickets;

import db.airport.models.Passenger;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Morgan
 */
public class PassengerInformationDialog extends javax.swing.JDialog {

	/**
	 * Creates new form PassengerInformationDialog
	 *
	 * @param parent
	 * @param title
	 * @param modal
	 * @param idFlight
	 * @param passengers
	 */
	public PassengerInformationDialog(Frame parent, String title, boolean modal,
		ArrayList<Passenger> passengers) {
		super(parent, title, modal);
		initComponents();
		DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
		for (Passenger passenger : passengers) {
			dcbm.addElement(passenger);
		}
		passengersCB.setModel(dcbm);
		passengersCB.setSelectedIndex(-1);
	}

	/**
	 *
	 * @param enable
	 */
	private void enableInfoPanel(boolean enable) {
		lastNameTF.setEnabled(enable);
		firstNameTF.setEnabled(enable);
		ageTF.setEnabled(enable);
		mRB.setEnabled(enable);
		fRB.setEnabled(enable);
		idTF.setEnabled(enable);
		if (enable) {
			lastNameTF.setText("");
			firstNameTF.setText("");
			ageTF.setText("");
			idTF.setText("");
		}
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderBG = new javax.swing.ButtonGroup();
        newBG = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        newPanel = new javax.swing.JPanel();
        newLabel = new javax.swing.JLabel();
        existsRB = new javax.swing.JRadioButton();
        newRB = new javax.swing.JRadioButton();
        passengersCB = new javax.swing.JComboBox<>();
        infoPanel = new javax.swing.JPanel();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTF = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTF = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        ageTF = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        mRB = new javax.swing.JRadioButton();
        fRB = new javax.swing.JRadioButton();
        idLabel = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        savePanel = new javax.swing.JPanel();
        nbLabel = new javax.swing.JLabel();
        nbTF = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        titleLabel.setText("Réservation de billets");

        newLabel.setText("Passager existant ?");

        newBG.add(existsRB);
        existsRB.setSelected(true);
        existsRB.setText("oui");
        existsRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                existsRBItemStateChanged(evt);
            }
        });

        newBG.add(newRB);
        newRB.setText("non");

        passengersCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        passengersCB.setMaximumSize(new java.awt.Dimension(64, 26));
        passengersCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                passengersCBItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout newPanelLayout = new javax.swing.GroupLayout(newPanel);
        newPanel.setLayout(newPanelLayout);
        newPanelLayout.setHorizontalGroup(
            newPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(existsRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newRB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(newPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(passengersCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        newPanelLayout.setVerticalGroup(
            newPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newLabel)
                    .addComponent(existsRB)
                    .addComponent(newRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passengersCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lastNameLabel.setText("Nom du passager principal :");

        lastNameTF.setEnabled(false);

        firstNameLabel.setText("Prénom du passager principal :");

        firstNameTF.setEnabled(false);

        ageLabel.setText("Age du passager principal :");

        ageTF.setEnabled(false);

        genderLabel.setText("sexe du passager principal :");

        genderBG.add(mRB);
        mRB.setSelected(true);
        mRB.setText("homme");
        mRB.setEnabled(false);

        genderBG.add(fRB);
        fRB.setText("femme");
        fRB.setEnabled(false);

        idLabel.setText("Numéro d'identification du passager principal :");

        idTF.setEnabled(false);

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(genderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fRB)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(idLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idTF))
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(infoPanelLayout.createSequentialGroup()
                                        .addComponent(lastNameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(infoPanelLayout.createSequentialGroup()
                                        .addComponent(firstNameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(infoPanelLayout.createSequentialGroup()
                                        .addComponent(ageLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(mRB)
                    .addComponent(fRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nbLabel.setText("nombre de passager(s) :");

        nbTF.setText("1");

        saveButton.setText("Enregistrer");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout savePanelLayout = new javax.swing.GroupLayout(savePanel);
        savePanel.setLayout(savePanelLayout);
        savePanelLayout.setHorizontalGroup(
            savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nbLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nbTF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        savePanelLayout.setVerticalGroup(
            savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nbLabel)
                    .addComponent(nbTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(savePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 *
	 * @param evt
	 */
    private void passengersCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_passengersCBItemStateChanged
		if (passengersCB.getSelectedIndex() != -1) {
			Passenger selected = (Passenger) passengersCB.getSelectedItem();
			lastNameTF.setText(selected.getLastName());
			firstNameTF.setText(selected.getFirstName());
			ageTF.setText(selected.getAge() + "");
			if (selected.getGender() == 'M') mRB.setSelected(true);
			else fRB.setSelected(true);
			idTF.setText(selected.getNumId());
		}
    }//GEN-LAST:event_passengersCBItemStateChanged

	/**
	 *
	 * @param evt
	 */
    private void existsRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_existsRBItemStateChanged
		if (existsRB.isSelected()) {
			enableInfoPanel(false);
			passengersCB.setEnabled(true);
		} else {
			enableInfoPanel(true);
			passengersCB.setEnabled(false);
			passengersCB.setSelectedIndex(-1);
		}
    }//GEN-LAST:event_existsRBItemStateChanged

	/**
	 * 
	 * @param evt 
	 */
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
		String msg = "";
		try {
			int nbPassengers = Integer.parseInt(nbTF.getText());
			if (nbPassengers < 1) {
				msg = "Il faut au moins un passager";
				JOptionPane.showMessageDialog(this, msg, "Attention", JOptionPane.ERROR_MESSAGE);
			} else {
				Passenger p;
				if (newRB.isSelected()) {
					int agePassenger = Integer.parseInt(ageTF.getText());
					char gender = (mRB.isSelected()) ? 'M' : 'F';
					p = new Passenger(lastNameTF.getText(), firstNameTF.getText(), agePassenger, gender);
					p.setNumId(idTF.getText());
				} else p = (Passenger) passengersCB.getSelectedItem();
				((AppTicketsForm)getParent()).setPassenger(p);
				((AppTicketsForm)getParent()).setNbPassengers(nbPassengers);
				this.dispose();
			}
		} catch (NumberFormatException e) {
			msg = "vous ne pouvez encoder que des chiffres pour l'age et le nombre de passagers";
			JOptionPane.showMessageDialog(this, msg, "Attention", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_saveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTF;
    private javax.swing.JRadioButton existsRB;
    private javax.swing.JRadioButton fRB;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTF;
    private javax.swing.ButtonGroup genderBG;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTF;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTF;
    private javax.swing.JRadioButton mRB;
    private javax.swing.JLabel nbLabel;
    private javax.swing.JTextField nbTF;
    private javax.swing.ButtonGroup newBG;
    private javax.swing.JLabel newLabel;
    private javax.swing.JPanel newPanel;
    private javax.swing.JRadioButton newRB;
    private javax.swing.JComboBox<String> passengersCB;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel savePanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
