package application.jiachat;

import crypto.utilities.CryptoUtilities;
import java.security.SecureRandom;
import java.util.Arrays;
import java.util.Date;
import javax.swing.JOptionPane;
import requestresponse.impl.IACOP.RequestIACOP;
import requestresponse.impl.IACOP.ResponseIACOP;
import requestresponse.multithread.BasicLoginDialog;
import requestresponse.multithread.abstracts.AbstractApplicationForm;
import requestresponse.multithread.interfaces.Response;

/**
 *
 * @author Morgan
 */
public class ChatLoginDialog extends BasicLoginDialog {
	
	private String infoUDP, clientName;

	/**
	 * Creates new form ChatLoginDialog
	 *
	 * @param parent
	 * @param modal
	 */
	public ChatLoginDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal, true);
		initComponents();
	}

	/**
	 * 
	 * @return 
	 */
	String getInfoUDP() {
		return infoUDP;
	}
	
	/**
	 * 
	 * @return 
	 */
	String getClientName() {
		return clientName;
	}
	
	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeButtonGroup = new javax.swing.ButtonGroup();
        agentPanel = new javax.swing.JPanel();
        agentLabel = new javax.swing.JLabel();
        agentRB = new javax.swing.JRadioButton();
        loginLabel = new javax.swing.JLabel();
        loginTF = new javax.swing.JTextField();
        pwdLabel = new javax.swing.JLabel();
        pwdTF = new javax.swing.JTextField();
        travelerPanel = new javax.swing.JPanel();
        travelerLabel = new javax.swing.JLabel();
        travelerRB = new javax.swing.JRadioButton();
        ticketLabel = new javax.swing.JLabel();
        ticketTF = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        agentLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        agentLabel.setText("Agent");

        typeButtonGroup.add(agentRB);
        agentRB.setSelected(true);
        agentRB.setText("Je suis un agent");
        agentRB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                agentRBStateChanged(evt);
            }
        });

        loginLabel.setText("Login :");

        pwdLabel.setText("Password :");

        javax.swing.GroupLayout agentPanelLayout = new javax.swing.GroupLayout(agentPanel);
        agentPanel.setLayout(agentPanelLayout);
        agentPanelLayout.setHorizontalGroup(
            agentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(agentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agentLabel)
                    .addGroup(agentPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(agentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(agentPanelLayout.createSequentialGroup()
                                .addComponent(loginLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loginTF))
                            .addComponent(agentRB)
                            .addGroup(agentPanelLayout.createSequentialGroup()
                                .addComponent(pwdLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pwdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        agentPanelLayout.setVerticalGroup(
            agentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agentRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(agentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel)
                    .addComponent(loginTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(agentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdLabel)
                    .addComponent(pwdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        travelerLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        travelerLabel.setText("Voyageur");

        typeButtonGroup.add(travelerRB);
        travelerRB.setText("Je suis un voyageur");
        travelerRB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                travelerRBStateChanged(evt);
            }
        });

        ticketLabel.setText("N° de billet :");

        ticketTF.setEnabled(false);

        javax.swing.GroupLayout travelerPanelLayout = new javax.swing.GroupLayout(travelerPanel);
        travelerPanel.setLayout(travelerPanelLayout);
        travelerPanelLayout.setHorizontalGroup(
            travelerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(travelerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(travelerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(travelerLabel)
                    .addGroup(travelerPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(travelerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(travelerPanelLayout.createSequentialGroup()
                                .addComponent(ticketLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ticketTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(travelerRB))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        travelerPanelLayout.setVerticalGroup(
            travelerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(travelerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(travelerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(travelerRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(travelerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketLabel)
                    .addComponent(ticketTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(travelerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(agentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(travelerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginButton)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	/**
	 * 
	 * @param evt 
	 */
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
		ResponseIACOP res = null;
		if (agentRB.isSelected()) {
			clientName = loginTF.getText();
			int rand = (new SecureRandom()).nextInt();
			long time = (new Date()).getTime();
			byte[] saltedPwd = CryptoUtilities.makeDigest(pwdTF.getText(), rand, time);
			Object cu[] = {RequestIACOP.EMPLOYEE, clientName, saltedPwd, rand, time};
			res = (ResponseIACOP) ((AbstractApplicationForm)getParent())
				.connectToServer(new RequestIACOP(RequestIACOP.LOGIN_GROUP, cu));
		} else if (travelerRB.isSelected()) {
			clientName = ticketTF.getText();
			Object cu[] = {RequestIACOP.TRAVELER, clientName};
			res = (ResponseIACOP) ((AbstractApplicationForm)getParent())
				.connectToServer(new RequestIACOP(RequestIACOP.LOGIN_GROUP, cu));
		}
		if (res == null) loginOK = false;
		else if (res.getCode() == ResponseIACOP.LOGIN_GROUP_OK) {
			loginOK = true;
			infoUDP = (String) res.getChargeUtile();
			this.setVisible(false);
		} else JOptionPane.showMessageDialog(this, res.getChargeUtile(), "Erreur", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_loginButtonActionPerformed

	/**
	 * 
	 * @param evt 
	 */
    private void agentRBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_agentRBStateChanged
        loginTF.setEnabled(agentRB.isSelected());
		pwdTF.setEnabled(agentRB.isSelected());
    }//GEN-LAST:event_agentRBStateChanged

	/**
	 * 
	 * @param evt 
	 */
    private void travelerRBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_travelerRBStateChanged
        ticketTF.setEnabled(travelerRB.isSelected());
    }//GEN-LAST:event_travelerRBStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agentLabel;
    private javax.swing.JPanel agentPanel;
    private javax.swing.JRadioButton agentRB;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField loginTF;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JTextField pwdTF;
    private javax.swing.JLabel ticketLabel;
    private javax.swing.JTextField ticketTF;
    private javax.swing.JLabel travelerLabel;
    private javax.swing.JPanel travelerPanel;
    private javax.swing.JRadioButton travelerRB;
    private javax.swing.ButtonGroup typeButtonGroup;
    // End of variables declaration//GEN-END:variables
}
