package server.payment;

import requestresponse.multithread.abstracts.ConsoleServerForm;
import server.multithread.abstracts.ThreadServer;
import server.multithread.extend.ThreadServerMultiRequest;
import server.multithread.impl.ListTasks;

/**
 *
 * @author Morgan
 */
public class ServerPaymentForm extends ConsoleServerForm {
	
	private int port_payment;
	private ThreadServer ts_payment;

	/**
	 * Creates new form ServerPaymentForm
	 */
	public ServerPaymentForm() {
		super("Serveur Paiement");
		super.setPropertiesFileName("serverpayment.properties");
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ServerPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ServerPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ServerPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ServerPaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				ServerPaymentForm spf = new ServerPaymentForm();
				spf.setLocationRelativeTo(null);
				spf.setVisible(true);
			}
		});
	}

	/**
	 * 
	 */
	@Override
	protected void serverStop() {
		if (ts_payment.isAlive()) {
			ts_payment.doStop();
			TraceEvents("server#stop paymment#main");
		}
	}

	/**
	 * 
	 */
	@Override
	protected void serverStart() {
		port_payment = Integer.parseInt(properties.getProperty("PORT_PAYMENT"));
		ts_payment = new ThreadServerMultiRequest("Payment", port_payment, this, new ListTasks());
		ts_payment.start();
		TraceEvents("server#start payment#main");
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
