DROP DATABASE IF EXISTS DB_Airport;
CREATE DATABASE IF NOT EXISTS DB_Airport DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE DB_Airport;
/*
DROP TABLE IF EXISTS Languages;
DROP TABLE IF EXISTS Luggages;
DROP TABLE IF EXISTS Tickets;
DROP TABLE IF EXISTS Passengers;
DROP TABLE IF EXISTS Flights;
DROP TABLE IF EXISTS Destination;
DROP TABLE IF EXISTS Zones;
DROP TABLE IF EXISTS Airlines;
DROP TABLE IF EXISTS Planes;
DROP TABLE IF EXISTS Agents;
DROP TABLE IF EXISTS Employer;
#*/
CREATE TABLE IF NOT EXISTS Employer
(	Id INT(11) NOT NULL AUTO_INCREMENT
,	Name VARCHAR(100) NOT NULL UNIQUE
,	Certificate VARCHAR(100)
,	PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS Agents 
(	Id INT(11) NOT NULL AUTO_INCREMENT
,	Login VARCHAR(30) NOT NULL UNIQUE
,	Password VARCHAR(30) NOT NULL
,	WorksFor INT(11) NOT NULL
,	PRIMARY KEY (Id)
,	FOREIGN KEY (WorksFor) REFERENCES Employer(Id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS Planes
(	Id INT(11) NOT NULL AUTO_INCREMENT
,	Check_OK BOOL NOT NULL DEFAULT FALSE
,	NbSeats INT(4) NOT NULL
,	PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS Airlines
(	Id VARCHAR(100) NOT NULL UNIQUE
,	PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

CREATE TABLE IF NOT EXISTS Zones
(	Id VARCHAR(15) NOT NULL UNIQUE
,	PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Destination
(	Id VARCHAR(50) NOT NULL UNIQUE
,	Distance INT(5) NOT NULL
,	RefZone VARCHAR(15) NOT NULL
,	PRIMARY KEY (Id)
,	FOREIGN KEY (RefZone) REFERENCES Zones(Id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Flights
(	Id INT(4) NOT NULL UNIQUE
,	RefDestination VARCHAR(50) NOT NULL
,	RefAirline VARCHAR(100) NOT NULL
,	DepartureDate DATE NOT NULL
,	DepartureTime VARCHAR(10) NOT NULL
,	ETA VARCHAR(10) NOT NULL
,	ArrivalTime VARCHAR(10) DEFAULT NULL
,	RefPlane INT(11) NOT NULL
,	Price FLOAT NOT NULL
,	PRIMARY KEY (Id)
,	FOREIGN KEY (RefDestination) REFERENCES Destination(Id) ON UPDATE CASCADE
,	FOREIGN KEY (RefAirline) REFERENCES Airlines(Id) ON UPDATE CASCADE
,	FOREIGN KEY (RefPlane) REFERENCES Planes(Id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DELIMITER $$
#DROP TRIGGER IF EXISTS Ticket_Price $$
CREATE TRIGGER Ticket_Price BEFORE INSERT ON Flights FOR EACH ROW
BEGIN
	DECLARE km INT(5);
	if (isnull(new.Price) ) then
		SET km = (SELECT Distance FROM Destination WHERE Id = new.RefDestination);
        SET new.Price = km * 0.07;
	END IF;
END $$
DELIMITER ;

CREATE TABLE IF NOT EXISTS Passengers
(	Id VARCHAR(200) NOT NULL UNIQUE
,	LastName VARCHAR(100) NOT NULL
,	FirstName VARCHAR(100) NOT NULL
,	NumId VARCHAR(30) DEFAULT NULL
,	Age INT(3) NOT NULL
,	Gender CHAR(1) NOT NULL
,	PRIMARY KEY (Id)
,	CONSTRAINT ck_gender CHECK(Gender IN ('M', 'F'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DELIMITER $$
#DROP TRIGGER IF EXISTS Id_Passenger $$
CREATE TRIGGER Id_Passenger BEFORE INSERT ON Passengers FOR EACH ROW
	if (isnull(new.Id) ) then
		SET new.Id = concat(upper(left(new.FirstName, 2)), upper(new.LastName));
	end if;
$$
DELIMITER ;

CREATE TABLE IF NOT EXISTS Clients 
(	Id INT(11) NOT NULL AUTO_INCREMENT
,	Login VARCHAR(30) NOT NULL UNIQUE
,	Password VARCHAR(30) NOT NULL
,	RefPassenger VARCHAR(200) NOT NULL
,	PRIMARY KEY (Id)
,	FOREIGN KEY (RefPassenger) REFERENCES Passengers(Id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS Tickets
(	Id VARCHAR(25) NOT NULL UNIQUE
,	RefPassenger VARCHAR(200) NOT NULL
,	RefFlight INT(4) NOT NULL
,	Paid BOOL NOT NULL DEFAULT FALSE
,	PRIMARY KEY (Id)
,	FOREIGN KEY (RefPassenger) REFERENCES Passengers(Id) ON UPDATE CASCADE
,	FOREIGN KEY (RefFlight) REFERENCES Flights(Id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

DELIMITER $$
#DROP TRIGGER IF EXISTS Id_Ticket $$
CREATE TRIGGER Id_Ticket BEFORE INSERT ON Tickets FOR EACH ROW
BEGIN
	DECLARE d VARCHAR(10);
    DECLARE num INT(11);
    IF (isnull(new.Id) ) THEN
		SET d = (SELECT date_format(DepartureDate, '%d%m%Y') FROM flights WHERE id = new.RefFlight);
		SET num = (SELECT count(*) FROM tickets WHERE RefFlight = new.RefFlight) + 1;
		SET new.Id = concat(new.RefFlight, '-', d, '-00', num);
	END IF;
END $$
DELIMITER ;

CREATE TABLE IF NOT EXISTS Luggages
(	Id VARCHAR(100) NOT NULL UNIQUE
,	Suitcase BOOL NOT NULL DEFAULT TRUE
,	Weight FLOAT NOT NULL
,	Received BOOL NOT NULL DEFAULT FALSE
,	Loaded CHAR(1) NOT NULL DEFAULT 'N'
,	CustomChecked BOOL NOT NULL DEFAULT FALSE
,	Comments VARCHAR(2000) DEFAULT NULL
,	RefTicket VARCHAR(25) NOT NULL
,	PRIMARY KEY (Id)
,	FOREIGN KEY (RefTicket) REFERENCES tickets(Id) ON UPDATE CASCADE ON DELETE CASCADE
,	CONSTRAINT ck_loaded CHECK(Loaded IN ('N', 'Y', 'R'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DELIMITER $$
#DROP TRIGGER IF EXISTS Id_Luggage $$
CREATE TRIGGER Id_Luggage BEFORE INSERT ON Luggages FOR EACH ROW
BEGIN
	DECLARE p VARCHAR(200);
    DECLARE num INT(11);
    IF (isnull(new.Id) ) THEN
		SET p = (SELECT RefPassenger FROM tickets WHERE Id = new.RefTicket);
        SET num = (SELECT count(*) FROM luggages WHERE RefTicket = new.RefTicket) + 1;
		SET new.Id = concat(left(new.RefTicket, 4), p, substr(new.RefTicket FROM 4), '-00', num);
	END IF;
END $$
DELIMITER ;

CREATE TABLE Languages
(	Id VARCHAR(2) NOT NULL UNIQUE
,	Name VARCHAR(50) NOT NULL
,	PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

