CREATE USER db_journaldebord IDENTIFIED BY azerty
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT ACCOUNT UNLOCK;
GRANT CONNECT TO db_journaldebord;
GRANT RESOURCE TO db_journaldebord;
GRANT EXECUTE ON SYS.DBMS_LOCK TO db_journaldebord;
ALTER USER db_journaldebord QUOTA 5M ON USERS;